exec-once = gsettings set $gnome-schema gtk-theme 'Gruvbox-Material-Dark'
exec-once = gsettings set $gnome-schema icon-theme 'Gruvbox-Dark-Plus'
exec-once = gsettings set $gnome-schema cursor-theme 'Bibata-Modern-Classic'
exec-once = gsettings set $gnome-schema font-name 'Inter Nerd Font Propo'

# Toolkit Backend Variables
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland # Run SDL2 applications on Wayland. Remove or set to x11 if games that provide older versions of SDL cause compatibility issues
env = CLUTTER_BACKEND,wayland


# XDG Specifications
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland


# QT Variables
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt5ct


# Theming
env = XCURSOR_SIZE,24                                                                 
env = HYPRCURSOR_SIZE,24                                                              
env = HYPRCURSOR_THEME,Bibata-Modern-Classic  
env = GDK_SCALE,1.25
env = QT_STYLE_OVERRIDE,kvantum
