# -------------------------------------------------------------------
# Window Rules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# -------------------------------------------------------------------

# You'll probably like this.
windowrulev2 =suppressevent maximize, class:.*

# Firefox Picture-in-Picture fixes
windowrulev2 = pin,class:(firefox),title:(Picture-in-Picture)
windowrulev2 = float,class:(firefox),title:(Picture-in-Picture)
windowrulev2 = move 990 44, class:(firefox),title:(Picture-in-Picture)
windowrulev2 = size 542 305, class:(firefox),title:(Picture-in-Picture)
windowrulev2 = opacity 1.0 override,class:(firefox),title:(Picture-in-Picture)

# Pavucontrol
windowrulev2 = float,class:(pavucontrol)
windowrulev2 = move 1018 41,class:(pavucontrol)

# KDE authentication agent
windowrulev2 = float, class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = center, class:^(org.kde.polkit-kde-authentication-agent-1)$
windowrulev2 = size 470 220, class:^(org.kde.polkit-kde-authentication-agent-1)$